version: '3'
services:
  mySQLContainer:
    image: mysql
    container_name: mySQLContainer
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: friending_test_db
      MYSQL_USER: donggil
      MYSQL_PASSWORD: '${DB_PASSWORD}'
