version: '3'
services:
  mySQLContainer:
    image: mysql
    container_name: mySQLContainer
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: friending_test_db
      MYSQL_USER: donggil
      MYSQL_PASSWORD: '${DB_PASSWORD}'
